/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Params {
  query: string
  filename: string
  ignoreCase: boolean
}
export declare function search(params: Params): void
